---
# This is the configuration file for the Nanopore cDNA differential expression tutorial.
# The configuration must be specified in YAML format

# indentation is required as in this template - a single indent is 4 spaces


pipeline: "Nanopore cDNA gene expression profiling"

reference_genome: "ftp://ftp.ensembl.org/pub/release-94/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz"

genome_annotation: "ftp://ftp.ensembl.org/pub/release-94/gtf/homo_sapiens/Homo_sapiens.GRCh38.94.gtf.gz"

Samples:
    - "Condition 1":   # this is a group 
        A1: "RawData/condition1_rep1.fastq.gz"    # filename pairs must be maintained - identifier and filename
        A2: "RawData/condition1_rep2.fastq.gz"
        A3: "RawData/condition1_rep3.fastq.gz"

    - "Condition 2":  # this is another group - names are arbitrary but must be unique
        B1: "RawData/condition2_rep1.fastq.gz"
        B2: "RawData/condition2_rep2.fastq.gz"
        B3: "RawData/condition2_rep3.fastq.gz"
        
referenceGroup: "Condition 1"   # this name *must* match one of the group names       

readCountMinThreshold: 10   # what is the minimum number of transcripts for a gene feature to be considered
lfcThreshold : 1            # minimum required log2 fold change for differential expression analysis
adjPValueThreshold: 0.05    # adjusted p-value threshold for differential expression analysis

tutorialText: FALSE
# please change the tutorialText: value to FALSE to mask the tutorial instructions


