channels:
  - bioconda
  - conda-forge
  - r
  - sagrudd
dependencies:
  - snakemake-minimal
  - python
  - samtools
  - minimap2
  - r-essentials
  - r
  - rstudio
  - nanopore-r-cdna-deseq2
  - openjdk
  - graphviz  # required for dag display
  - imagemagick
  
